python -u main.py \
        --nodes 1 \
        --gpus 2 \
        --rank 0 \
        --nepochs 60 \
        --epochs-done 0 \
        --train-path '/users/PAS1939/vishal/datasets/librispeech/train_full_960.csv' \
        --logging-file 'logs/debug.log' \
        --save-path '/users/PAS1939/vishal/saved_models/debug.pth.tar' \
        --ckpt-path '/users/PAS1939/vishal/saved_models/debug.pth.tar' \
        --enc-type 'lstm' \
        --batch-size 8 \
        --bsz-small 4 \
        --n-layer 6 \
        --in-dim 320 \
        --hid-tr 1280 \
        --hid-pr 1024 \
        --lr 0.001 \
        --clip 10.0 \
        --dropout 0.25
