python -u main.py \
        --nodes 4 \
        --gpus 1 \
        --rank 3 \
        --nepochs 60 \
        --epochs-done 0 \
        --address 'p0319' \
        --train-path '/users/PAS1939/vishal/datasets/librispeech/train_full_960.csv' \
        --logging-file 'logs/debug1.log' \
        --save-path '/users/PAS1939/vishal/saved_models/debug1' \
        --ckpt-path '' \
        --enc-type 'lstm' \
        --batch-size 64 \
        --bsz-small 8 \
        --n-layer 6 \
        --in-dim 320 \
        --hid-tr 1280 \
        --hid-pr 1024 \
        --lr 0.001 \
        --clip 10.0 \
        --dropout 0.25
